version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:

      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique:
              config:
                  fail_calc: "sum(n_records)"
                  limit: 10
                  severity: error
                  error_if: ">1000"
                  warn_if: ">1"

      - name: host_id
        description: The hosts's id. References the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id




  - name: dim_hosts_cleansed
    description: Cleansed table for the Airbnb hosts
    columns:
      - name: host_id
        description: The id of the host. This is the primary key.
        tests:
          - not_null
          - unique
      
      - name: host_name
        description: The name of the hosts
        tests:
          - not_null
      
      - name: is_superhost
        description: Defines whether the hosts is a superhost.
        tests:
          - accepted_values:
              values: ['t', 'f']

      - name: minimum_nights
        tests: 
          -  positive_value

